from django.contrib import admin
from .models import Banner, Teachers,NewsAndEvents,NewsAndEventImages,Toppers,Sports,SportsImages, CoCarricular, CoCarricularImages,ExtraCurricular,ExtraCurricularImages, Facilitie, FacilitieImages,SmartClass,SmartClassImages,LifeAtSchoolImages,LifeAtSchoolImages, LifeAtSchool, LifeAtSchoolImages,OrientationProgram, OrientationProgramImages, Gallery, GalleryImages, ParentFeedback, AdmissionCriterias,ClassRoutine,ClassRoutineImages,Award,AwardImages

admin.site.register(Banner)
admin.site.register(Teachers)
admin.site.register(NewsAndEvents)
admin.site.register(NewsAndEventImages)
admin.site.register(Toppers)
admin.site.register(Sports)
admin.site.register(SportsImages)
admin.site.register(CoCarricular)
admin.site.register(CoCarricularImages)
admin.site.register(ExtraCurricular)
admin.site.register(ExtraCurricularImages)
admin.site.register(Facilitie)
admin.site.register(FacilitieImages)
admin.site.register(SmartClass)
admin.site.register(SmartClassImages)
admin.site.register(LifeAtSchool)
admin.site.register(LifeAtSchoolImages)
admin.site.register(OrientationProgram)
admin.site.register(OrientationProgramImages)
admin.site.register(Gallery)
admin.site.register(GalleryImages)
admin.site.register(ParentFeedback)
admin.site.register(AdmissionCriterias)
admin.site.register(ClassRoutine)
admin.site.register(ClassRoutineImages)
admin.site.register(Award)
admin.site.register(AwardImages)
